name: CI

on:
  pull_request:
    paths:
      - 'domain/**'
      - 'tests/**'
      - 'package.json'
      - '.github/workflows/ci.yml'
  push:
    branches: [main]
    paths:
      - 'domain/**'
      - 'tests/**'
      - 'package.json'
      - '.github/workflows/ci.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

