name: Deploy API

on:
  push:
    branches: [main]
    paths:
      - 'domain/**'
      - 'scripts/generate-api.js'
      - '.github/workflows/deploy-api.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Generate API JSON
        run: node scripts/generate-api.js raw-api/v1.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./raw-api 