name: Validate Subdomain Request

on:
  pull_request:
    paths:
      - 'domain/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate JSON files
        run: |
          for file in domain/*.json; do
            echo "Validating $file..."
            jq 'select(.request and .request.sub and .request.owner and .request.owner.gh and .request.dns)' "$file" > /dev/null || {
              echo "::error file=$file::Invalid format. Required fields: request.sub, request.owner.gh, request.dns";
              exit 1;
            }
          done 